# Install numpy and import

In [2]:
!pip3 install numpy
import numpy as np

You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.


# How to create an empty and a full NumPy array?

In [17]:
empty_np_array = np.empty(shape=0) # empty numpy array
full_np_array = np.full(shape=20, fill_value=10) # numpy array with twenty 10s
empty_np_array, full_np_array

(array([], dtype=float64),
 array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10]))

# Create a Numpy array filled with all zeros

In [18]:
zeros_np_array = np.zeros(shape=20) # numpy array with twenty 0s
zeros_np_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

# Create a Numpy array filled with all ones

In [19]:
ones_np_array = np.ones(shape=20) # numpy array with twenty 1s
ones_np_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

# Check whether a Numpy array contains a specified row

In [23]:
specified_row_array = np.array([[1, 2, 3, 4, 5],
                                [6, 7, 8, 9, 10],
                                [11, 12, 13, 14, 15],
                                [16, 17, 18, 19, 20]
                              ])
[1, 2, 3, 4, 5] in specified_row_array.tolist(), [6, 7, 8, 9, 10] in specified_row_array.tolist(), [11, 12, 13, 14, 15] in specified_row_array.tolist(), [16, 17, 18, 19, 20] in specified_row_array.tolist()

(True, True, True, True)

# How to Remove rows in Numpy array that contains non-numeric values?

In [25]:
non_numeric_np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, np.nan])
non_numeric_np_array[~np.isnan(non_numeric_np_array)]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.])

# Remove single-dimensional entries from the shape of an array

In [34]:
to_squeeze_np_array = np.array([[[0], [1], [2]]])
to_squeeze_np_array.shape
np.squeeze(to_squeeze_np_array).shape

(3,)

# Find the number of occurrences of a sequence in a NumPy array

In [36]:
occurrences_sequence_np_array = np.array([[0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]) # 5 times 0, 1 occur
out = repr(occurrences_sequence_np_array).count("0, 1")
out

5

# Find the most frequent value in a NumPy array

In [39]:
most_frequent_in_np_array = np.array([0, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4]) # should be 4
np.bincount(most_frequent_in_np_array).argmax() # argmax should return the one that has the biggest frequency

4

# Combining a one and a two-dimensional NumPy Array

In [47]:
to_combine_2d = np.array([[1, 2, 3, 4, 5],
                          [6, 7, 8, 9, 10],
                          [11, 12, 13, 14, 15],
                          [16, 17, 18, 19, 20]
                        ])
to_combine_1d = np.array([21, 22, 23, 24, 25])               
for a, b in np.nditer([to_combine_1d, to_combine_2d]):
    print("%d:%d" % (a, b))

21:1
22:2
23:3
24:4
25:5
21:6
22:7
23:8
24:9
25:10
21:11
22:12
23:13
24:14
25:15
21:16
22:17
23:18
24:19
25:20


# How to build an array of all combinations of two NumPy arrays?

In [51]:
combinations_np_array_1 = np.array([0, 1])
combinations_np_array_2 = np.array([2, 3])
combination_np_array = np.array(np.meshgrid(combinations_np_array_1, combinations_np_array_2)).T.reshape(-1, 2)
combination_np_array

array([[0, 2],
       [0, 3],
       [1, 2],
       [1, 3]])

# How to add a border around a NumPy array?

In [54]:
bordered_np_array = np.ones((2, 2), dtype=np.int64)
bordered_np_array = np.pad(array=bordered_np_array, pad_width=1, mode="constant", constant_values=1111)
bordered_np_array

array([[1111, 1111, 1111, 1111],
       [1111,    1,    1, 1111],
       [1111,    1,    1, 1111],
       [1111, 1111, 1111, 1111]], dtype=int64)

# How to compare two NumPy arrays?

In [56]:
first_np_array = np.array([[1, 2], [3, 4]])
second_np_array = np.array([[1, 2], [3, 4]])
(first_np_array == second_np_array).all()

False

# How to check whether specified values are present in NumPy array?

In [58]:
to_check_specified_np_array = np.array([[1, 2, 3], [4, 5, 6]])
print(1 in to_check_specified_np_array)
print(2 in to_check_specified_np_array)
print(3 in to_check_specified_np_array)
print(4 in to_check_specified_np_array)
print(5 in to_check_specified_np_array)
print(6 in to_check_specified_np_array)
print(0 in to_check_specified_np_array)
print(7 in to_check_specified_np_array)

True
True
True
True
True
True
False
False


# How to get all 2D diagonals of a 3D NumPy array?

In [60]:
three_dimensional_np_array = np.arange(3 * 4 * 4).reshape(3, 4, 4)
print("Original array: ", three_dimensional_np_array)
diagonal_np_array = np.diagonal(three_dimensional_np_array, axis1=1, axis2=2)
diagonal_np_array

Original array:  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[ 0,  5, 10, 15],
       [16, 21, 26, 31],
       [32, 37, 42, 47]])

# Flatten a Matrix in Python using NumPy

In [68]:
two_dimensional_np_matrix = np.matrix([0, 1, 2, 3])
two_dimensional_np_matrix.flatten()

matrix([[0, 1, 2, 3]])

# Flatten a 2d numpy array into 1d array

In [65]:
two_dimensional_np_array = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
two_dimensional_np_array.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

# Move axes of an array to new positions

In [70]:
zeros_np_array = np.zeros((1, 2, 3, 4))
moved_axes_np_array = np.moveaxis(zeros_np_array, 0, -1).shape
moved_axes_np_array

(2, 3, 4, 1)

# Interchange two axes of an array

In [71]:
to_interchange_np_array = np.array([[2, 4, 6]])
swaped_axes_np_array = np.swapaxes(to_interchange_np_array, 0, 1)
swaped_axes_np_array

array([[2],
       [4],
       [6]])

# NumPy – Fibonacci Series using Binet Formula

In [72]:
a = np.arange(1, 11)
sqrtFive = np.sqrt(5)
alpha = (1 + sqrtFive) / 2
beta = (1 - sqrtFive) / 2
Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrtFive))
print("The first {} numbers of Fibonacci series are {} . ".format(len(a), Fn))

The first 10 numbers of Fibonacci series are [ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.] . 


# Counts the number of non-zero values in the array

In [74]:
a = np.array([0, 0, 0, 1, 2 ,3])
np.count_nonzero(a)

3

# Count the number of elements along a given axis

In [76]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.size(a)

8

# Trim the leading and/or trailing zeros from a 1-D array

In [77]:
a = np.array([0, 0, 0, 0, 1, 2, 3, 4, 5, 0, 0, 0, 0])
np.trim_zeros(a)

array([1, 2, 3, 4, 5])

# Change data type of given numpy array

In [80]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a.dtype)
a = a.astype("float64")
a, a.dtype

int32


(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 dtype('float64'))

# Reverse a numpy array

In [81]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.flip(a)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# How to make a NumPy array read-only?

In [85]:
print(a)
a.flags.writeable = False
a[0] = 100
a

[ 0  1  2  3  4  5  6  7  8  9 10]


ValueError: assignment destination is read-only

# Get the maximum value from given matrix

In [87]:
m = np.matrix(np.arange(12).reshape((3,4)))
print(m)
m.max()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


11

# Get the minimum value from given matrix

In [90]:
m, m.min()

(matrix([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 0)

# Find the number of rows and columns of a given matrix using NumPy

In [91]:
m.shape

(3, 4)

# Select the elements from a given matrix

In [94]:
np.take(m, [4, 4])

matrix([[4, 4]])

# Find the sum of values in a matrix

In [95]:
m.sum()

66

# Calculate the sum of the diagonal elements of a NumPy array

In [97]:
m = np.array([[55, 25, 15],
              [30, 44, 2],
              [11, 45, 77]
            ])
np.trace(m)

176

# Adding and Subtracting Matrices in Python

In [99]:
first_np_matrix = np.matrix([[1, 2], [3, 4]])
second_np_matrix = np.matrix([[1, 2], [3, 4]])
np.add(first_np_matrix, second_np_matrix), np.subtract(first_np_matrix, second_np_matrix)

(matrix([[2, 4],
         [6, 8]]),
 matrix([[0, 0],
         [0, 0]]))

# Ways to add row/columns in numpy array

In [100]:
m = np.matrix([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
column_to_be_added = np.array([1, 2, 3])
np.hstack((m, np.atleast_2d(column_to_be_added).T))

matrix([[ 1,  2,  3,  1],
        [45,  4,  7,  2],
        [ 9,  6, 10,  3]])